name = "tutor" # todo
#name = "akun-vless-sg" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routers]]
pattern = "sg.ibnuopenwrt.my.id"
custom_domain = true
[[routers]]
pattern = "nontontv.vidio.com.sg.ibnuopenwrt.my.id"
custom_domain = true
[[routers]]
pattern = "quiz.int.vidio.com.sg.ibnuopenwrt.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "24e27ef6-fbe5-48f2-bbc3-afa1a57daa4a"
